### ISSUE TITLE
Problem compiling on windows

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/elgato-stream-deck-clean-xl#1]
When this module is included via yarn on the sister project bitfocus/companion, this is unable to compile on windows. But successfully compiles on mac and linux.

The problem is in the module jpeg-turbo.

You need to install yasm for it to compile. On windows however, it has problems finding the projects include files for yasm.

```"yasm: FATAL: unable to open include file `jsimdcfg.inc'"```

So basically it seems that someone with some leet node-gyp skills could fix this easily.

Wanted: A fork of jpeg-turbo that compiles successfully on mac/win/linux when included by this module. (be sure to send a pull request upstream too) (PS. the sister project using this module uses yarn to fetch/compile the modules, and I have had some weird issues where npm does a better job at this, so make sure this works too)

**Comment by Julusian** [comment]
https://github.com/sorccu/node-jpeg-turbo/pull/13

**Comment by haakonnessjoen** [comment]
Solved by @Julusian <3

**Comment by haakonnessjoen** [comment]
Be sure to claim the reward!
